# Generated by Django 5.1.7 on 2025-03-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
