# Generated by Django 5.1.7 on 2025-03-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(default='', max_length=100)),
                ('about', models.CharField(default='', max_length=500)),
                ('visitable', models.BooleanField(default=True)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
